[project]
name = "hardfork"
requirements = []
cache_dir = "./.cache"

[accounts.testnet-deployer]
mnemonic = "sell invite acquire kitten bamboo drastic jelly vivid peace spawn twice guilt pave pen praise pork crisp unite giggle laundry steel canvas door creek thunder"
derivation = "m/44'/5757'/0'/0/0"

[contracts.barrel-nft]
path = "contracts/barrel-nft.clar"

[contracts.governance-token]
path = "contracts/governance-token.clar"

[contracts.treasury]
path = "contracts/treasury.clar"

[contracts.production-batch]
path = "contracts/production-batch.clar"

[contracts.presale]
path = "contracts/presale.clar"

[contracts.public-sale]
path = "contracts/public-sale.clar"

[contracts.batch-registry]
path = "contracts/batch-registry.clar"