[project]
name = "hardfork"
requirements = []
cache_dir = "./.cache"

[contracts.barrel-nft]
path = "contracts/barrel-nft.clar"

[contracts.governance-token]
path = "contracts/governance-token.clar"

[contracts.treasury]
path = "contracts/treasury.clar"