[network]
name = "devnet"

[devnet]
bitcoin_controller_enabled = false
orchestrator_port = 20446

[accounts.deployer]
mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing glory cousin green tomorrow spring wrist shed math olympic multiply hip blue scout claw"